include:
  - template: Security/License-Scanning.gitlab-ci.yml

stages:
  - test

go_test:
  image: "$GO_IMAGE"
  tags:
    - famedly
    - docker
  variables:
    GO_IMAGE: "docker.io/library/golang:1.19-bullseye"
  script:
    - go test
