---
on:
  push:
    branches: ["main"]
  pull_request:
    
jobs:
  go-test:
    name: Run go test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: go test
